### ISSUE TITLE
Example Running Error 

### ISSUE THREAD

**Issue by Sylarair** [shendurelab/MPRAflow#24]
Hi, 

When I tried to run the example on the web page (https://mpraflow.readthedocs.io/en/latest/association_example1.html#association-example), I got errors showed in the attached [figure1](https://drive.google.com/open?id=18OsssTSl5MDUhhSAdLY9Qk1HVr_W1jaD) and [figure2](https://drive.google.com/open?id=1oh3XES76tXoiDmTvlY6JDPDXv_pAUOcO).

My code is `nextflow run association.nf -w $path/Assoc_Basic/work --fastq-insert "$path/Assoc_Basic/data/SRR10800986_1.fastq.gz" --fastq-insertPE "$path/Assoc_Basic/data/SRR10800986_3.fastq.gz" --fastq-bc "$path/Assoc_Basic/data/SRR10800986_2.fastq.gz" --design "$path/Assoc_Basic/data/design.fa" --name assoc_basic `, and I tried it several times while getting the same running errors. Could anyone help me with this? Many thanks!

![image](https://user-images.githubusercontent.com/18133362/80279401-0fb63200-8730-11ea-88e3-a6ce3ca3575b.png)

<img width="840" alt="MPRAflow_bug2" src="https://user-images.githubusercontent.com/18133362/80279519-cca88e80-8730-11ea-9fe3-2e7a1c515dbc.png">

**Comment by Sylarair** [comment]
<img width="849" alt="Screen Shot 2020-04-25 at 7 57 13 PM" src="https://user-images.githubusercontent.com/18133362/80279409-1cd32100-8730-11ea-8ebb-340b7dcda0ac.png">

**Comment by Sylarair** [comment]
<img width="849" alt="Screen Shot 2020-04-25 at 7 57 13 PM" src="https://user-images.githubusercontent.com/18133362/80279429-3aa08600-8730-11ea-846b-ad41408dd8cb.png">

**Comment by visze** [comment]
Hey,

thank you for the issue. Can you tell us the nextflow version you are using?
Can you show me the files (with file sizes) that are present in the folder `work/89/74cc577009d099...`?

And is it possible to try the actual development version 2.1-dev (in the development branch)? Just to see if the error is still present. But it requires now nextflow version >=20.01 

Best,
Max

**Comment by Sylarair** [comment]
Hi,

Sorry for the late reply. The version of `nextflow` I am using is *19.10.0.5170*。

For your next question, There is no `89` under `work` folder (Attached file 1).

<img width="546" alt="Screen Shot 2020-05-06 at 4 55 56 PM" src="https://user-images.githubusercontent.com/18133362/81158349-76521000-8fba-11ea-8737-e67289b243cd.png">

**Comment by visze** [comment]
Ok then is difficult to find the error if `work/89/74cc577009d099...` is not available when the error appears there (according to your previous post).

I will run the workflow with your nextflow version and the tutorial dataset to try to reconstruct your error.

Maybe you can try the develop version in the meantime. Also you should check if the data (by `fastq-dump`) is downloaded completely. `fastq-dump` sometimes cancels the download without notifications. In the development documentation we now recommend to use `prefetch` first: https://mpraflow.readthedocs.io/en/development/association.html

**Comment by Sylarair** [comment]
Thanks for your reply. I tried develop version just now, and this time there is a different error (attached figure).

<img width="829" alt="Screen Shot 2020-05-06 at 6 40 32 PM" src="https://user-images.githubusercontent.com/18133362/81168331-6261da80-8fc9-11ea-8ede-868dca51ffea.png">

<img width="834" alt="Screen Shot 2020-05-06 at 6 43 35 PM" src="https://user-images.githubusercontent.com/18133362/81168397-80c7d600-8fc9-11ea-8d74-c0e333e7e104.png">

**Comment by Sylarair** [comment]
As for the data, I checked several times before, and all datasets are complete.

**Comment by visze** [comment]
oh. I am sorry. I changed it only in the development branch of my fork and forgot to push it to shedurelab.

Chan you pull the newest development and try it again?

Best,
Max

**Comment by Sylarair** [comment]
Sure. I'll try it at once. Thanks!

Best,
Qin

**Comment by Sylarair** [comment]
It worked! Thanks!

**Comment by Sylarair** [comment]
Hi,

I am facing new problem when running `nextflow run count.nf -w $local_path/Assoc_Basic/work --experiment-file "$local_path/Assoc_Basic/data/experiment.csv" --dir "$local_path/Assoc_Basic/data" --outdir $local_path"/Assoc_Basic/output" --design "$local_path/Assoc_Basic/data/design.fa" --association "${PWD}/outs/assoc_basic/assoc_basic_filtered_coords_to_barcodes.pickle"
`, which can be seen in the attached figure.

<img width="787" alt="Screen Shot 2020-05-27 at 3 25 35 PM" src="https://user-images.githubusercontent.com/18133362/82990156-526c7200-a02e-11ea-9a32-c56e33f5295a.png">

Could anyone help see this? Many thanks!

**Comment by Sylarair** [comment]
Also, there is another question. Need I precut adaptor in advance? Thanks!

**Comment by visze** [comment]
It looks like there is an empty file. Can you have a look at `HEPG2_2_counts.tsv` `HEPG2_1_counts.tsv` and `HEPG2_3_counts.tsv`. Should be in the `c9/5c4a3c` folder. If I am right the "error" appears before.

I also see that the threshold is hard-coded into the script:

https://github.com/shendurelab/MPRAflow/blob/d0a8e0c2a86ef986d4f1fa5ea0e637c5f7431da8/src/plot_perInsertCounts_correlation.R#L54

I will fix that. Do you use the development version again?

Finally, I think we should implement some quality checks after each process so that the user is able too see what goes wrong.

**Comment by Sylarair** [comment]
Thanks for your answer. What I was using is `dev`, and the results that I see under `c9/5c4a3c` are empty. 

<img width="825" alt="Screen Shot 2020-05-28 at 8 41 50 AM" src="https://user-images.githubusercontent.com/18133362/83085630-16cdb880-a0bf-11ea-9af8-076018fbbb85.png">

**Comment by visze** [comment]
cleaning up. Plese reopen if you still habe issues
