### ISSUE TITLE
Association.nf fails at map_element_barcodes step

### ISSUE THREAD

**Issue by bioarpit1** [shendurelab/MPRAflow#26]
Hi 
Thanks for read the doc documents and this pipeline. For me MPRAflow pipeline is working with test data set. When i try to run it using my own data i am getting this error executor >  local (8)
[86/77d0f6] process > count_bc_nolab (count)        [100%] 1 of 1 ✔
[05/e48b05] process > create_BWA_ref (make ref)     [100%] 1 of 1 ✔
[64/dede86] process > PE_merge (merge)              [100%] 2 of 2 ✔
[72/109d98] process > align_BWA_PE (align)          [100%] 2 of 2 ✔
[50/3605df] process > collect_chunks                [100%] 1 of 1 ✔
[01/dc4b71] process > map_element_barcodes (assign) [  0%] 0 of 1
[-        ] process > filter_barcodes               -
Error executing process > 'map_element_barcodes (assign)'

Caused by:
  Process `map_element_barcodes (assign)` terminated with an error exit status (1)

Command executed:

  echo "test assign inputs"
  echo 20
  echo 20
  echo barcode.fastq.gz
  zcat barcode.fastq.gz | head

  echo count_fastq.txt
  echo count_merged.txt
  cat count_fastq.txt
  cat count_merged.txt

  python /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/MPRAflow/src/nf_ori_map_barcodes.py /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/MPRAflow barcode.fastq.gz count_fastq.txt         s_merged.bam count_merged.txt assoc_15merbc_PE 20 20 n

Command exit status:
  1
In my experimental design i followed strategy from Klein et al., Nat comm 2018 paper, Thus i have random 5 mer barcode, I tried using random barcode association step you mentioned in protocol which is failing at (allign BWA step). Thus i created a list of barcodes by appending upstream 5 and downstream 5 bp (which will be constant). Thus my barcode diversity will be less to compensate this i gave stringent  min cov min frac option
this is my command 
 "nextflow run association.nf -w /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/data3/testSRR989 --mapq 20 --baseq 20  --fastq-insert "/net/hawkins/vol1/arpit/STARR_seq_fastafiles/STARRseqdata/test_15mer_paired_unpaired/dTC1_R1.fastq.gz" --fastq-insertPE "/net/hawkins/vol1/arpit/STARR_seq_fastafiles/STARRseqdata/test_15mer_paired_unpaired/dTC1_R2.fastq.gz" --fastq-bc "/net/hawkins/vol1/arpit/STARR_seq_fastafiles/STARRseqdata/test_15mer_paired_unpaired/barcode.fastq.gz" --design "/net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAflow/allergy-asthma_uniq.fasta" --min-cov 14 --min-frac 1 --name assoc_15merbc_PE"
but i can see from this 

MPRAflow v2.1"
=======================================================
Pipeline Name  : MPRAflow
Pipeline Version: 2.1
Fastq insert   : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/STARRseqdata/test_15mer_paired_unpaired/dTC1_R1.fastq.gz
fastq paired   : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/STARRseqdata/test_15mer_paired_unpaired/dTC1_R2.fastq.gz
Fastq barcode  : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/STARRseqdata/test_15mer_paired_unpaired/barcode.fastq.gz
design fasta   : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAflow/allergy-asthma_uniq.fasta
minimum BC cov : 3
map quality    : 20
base quality   : 20
cigar string   : n
min % mapped   : 0.5
Output dir     : outs
Run name       : assoc_15merbc_PE
Working dir    : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/data3/testSRR989
Container Engine: null
Current home   : /net/hawkins/vol1/home/arpitm
Current user   : arpitm
Current path   : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/MPRAflow
base directory : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/MPRAflow
Script dir     : /net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example/Assoc_Basic/data/MPRAflow
Config Profile : standard
=========================================
min bc coverage and min % mapped parameters hasnt change while running the above command where i changed --min-cov 14 --min-frac 1. 

Sorry for lengthy issue, I can provide any more information or test files i have used for my run 

Thanks
Arpit

**Comment by visze** [comment]
Hi Arpit,

can you show me the error of the map_element_barcodes (assign) process? You will find it under the working directory in this folder: `01/dc4b71`

thanks

Max

**Comment by bioarpit1** [comment]
Hi Max, 

thanks for your quick response, here i am attaching .command.err (screenshot) and .command.log file from the location you have mentioned
[.command.log](https://github.com/shendurelab/MPRAflow/files/4629402/default.command.log)
![image](https://user-images.githubusercontent.com/29548776/81954994-663fbf00-95be-11ea-83e8-e555c0e8ebbd.png)

Thanks

Arpit

**Comment by visze** [comment]
Thank you. Is there a file `assoc_15merbc_PE _coords_to_barcodes.pickle`? Maybe in the `01/dc4b71` folder or in the `/net/hawkins/vol1/arpit/STARR_seq_fastafiles/MPRAFLOW_example` folder or somewhere else? Is it possible to send me the file?

**Comment by bioarpit1** [comment]
Yes there is file assoc_15merbc_PE _coords_to_barcodes.pickle in 01/dc4b71, but it looks empty just few entry. what email id I should send as github is not supporting .pickle file upload. Attaching screenshot 
![image](https://user-images.githubusercontent.com/29548776/82116725-acad2f00-9720-11ea-8866-09a6fc5aa713.png)

**Comment by visze** [comment]
You find my mail here: https://kircherlab.bihealth.org/people/max.html

This error is something specific about you data. Or I think we can turn it
around our data is to specific and the process cannot handle all data. But
I am sure we can fix that.

Arpitm <notifications@github.com> schrieb am Sa., 16. Mai 2020, 11:55:

**Comment by visze** [comment]
Any update here?

**Comment by bioarpit1** [comment]
i have sent you the pickle  file you requested. If you want i can also share my test data i  used to generate the file.

**Comment by visze** [comment]
So I had a look at the data. You try to run STARR-seq with MPRAflow. In particular this dataset: https://www.nature.com/articles/s41467-019-10439-y

Have a look at the comment of @makirc here https://github.com/shendurelab/MPRAflow/issues/27#issuecomment-636515565
