### ISSUE TITLE
Error with Basic Association: map_element_barcodes error

### ISSUE THREAD

**Issue by townsk** [shendurelab/MPRAflow#34]
Hitting an error during the map_element_barcodes process in the nextflow.nf scripts. Any help appreciated!
<img width="1420" alt="Screen Shot 2021-03-03 at 4 17 13 PM" src="https://user-images.githubusercontent.com/56935409/109873575-ec0b2480-7c3b-11eb-89f0-d204a2f80fb3.png">

This is the error code: 
<img width="1668" alt="Screen Shot 2021-03-03 at 4 11 47 PM" src="https://user-images.githubusercontent.com/56935409/109873157-62f3ed80-7c3b-11eb-9162-539f2e146ac5.png">
<img width="1689" alt="Screen Shot 2021-03-03 at 4 12 03 PM" src="https://user-images.githubusercontent.com/56935409/109873191-6be4bf00-7c3b-11eb-9024-03f2fa206993.png">
<img width="1688" alt="Screen Shot 2021-03-03 at 4 12 16 PM" src="https://user-images.githubusercontent.com/56935409/109873171-66877480-7c3b-11eb-90ad-6bd0449a8784.png">
<img width="1689" alt="Screen Shot 2021-03-03 at 4 12 30 PM" src="https://user-images.githubusercontent.com/56935409/109873243-7f902580-7c3b-11eb-8340-48e29cca1b67.png">
<img width="1676" alt="Screen Shot 2021-03-03 at 4 12 43 PM" src="https://user-images.githubusercontent.com/56935409/109873216-769f5400-7c3b-11eb-8838-8ca06ba52451.png">

**Comment by visze** [comment]
Hey. I hope I can help and I maybe found something.

You are using the same fasq files for assignment and BC reads. This have to be two seperate fastq files. Have a look at the documentation: https://mpraflow.readthedocs.io/en/latest/association.html#fastq-files

**Comment by townsk** [comment]
Wow, I cannot believe I missed that. Thanks! 

Also for anyone else having similar issues (minus the file mishap), realized my numpy package needed to be updated.
