### ISSUE TITLE
BassicAssociation: filter_barcodes error - issue with pyarrow

### ISSUE THREAD

**Issue by townsk** [shendurelab/MPRAflow#36]
Any suggestions for "ModuleNotFoundError: No module named 'pyarrow'?"

Prior to running the association script I installed pyarrow: 
conda install pyarrow -c conda-forge

<img width="1725" alt="Screen Shot 2021-03-04 at 3 56 42 PM" src="https://user-images.githubusercontent.com/56935409/110029776-e2002900-7d02-11eb-98cb-f6c7fd4d77e9.png">

Thanks!

**Comment by townsk** [comment]
Okay pyarrow issue resolved - now having issues with pandas. Specifically loading the module pandas._libs.interval. See error code below:
<img width="1573" alt="Screen Shot 2021-03-04 at 4 37 10 PM" src="https://user-images.githubusercontent.com/56935409/110034491-833dae00-7d08-11eb-878f-a16498f1df1b.png">

**Comment by visze** [comment]
Hey. The pyarrow issue is a bit strange, because we are using nextflow with conda! 

Here we define the conda environment for the `filter_barcode` step: https://github.com/shendurelab/MPRAflow/blob/fd5ff26b04686196ac37ed849afbcfc01b303b3f/association.nf#L494

And here you can find `pyarrow`in the in the environment: `https://github.com/shendurelab/MPRAflow/blob/fd5ff26b04686196ac37ed849afbcfc01b303b3f/conf/mpraflow_py36.yml#L108`

Maybe you nextflow run does not use conda, just your base eenvironment? This becomes very important for the count step because here we have script with python 2 and python 3.

When you run the scipt by yourselv you have to use also the environment:

```bash
conda env create -n mpraflow_p36 - f conf/mpraflow_py36.yml
conda activate mpraflow_p36
python src/nf_filter_barcodes.py
```

**Comment by townsk** [comment]
Hi again, 

I've done what you recommended and that resolved the initial issue. Seems there is some issue with the nf_filter_barcodes.py file. Here is the error code I'm getting. 

<img width="1130" alt="Screen Shot 2021-03-08 at 10 10 14 AM" src="https://user-images.githubusercontent.com/56935409/110340255-0efc5680-7ff7-11eb-865c-a7d25960424c.png">

**Comment by townsk** [comment]
![Uploading Screen Shot 2021-03-08 at 1.44.15 PM.png…]()

**Comment by visze** [comment]
@townsk you addes some comments yesterday ( saw them in my mails) but they are not listed anymore. Just let me know if you need further help

**Comment by visze** [comment]
The runtime of `nf_filter_barcodes.py` script depends on the size of the input. But in theory it should be one of the quicker scripts. Definetifely under 1 hour.

But maybe you have some issues with plotting the violin plots. Can you comment out these lines: 
https://github.com/shendurelab/MPRAflow/blob/fd5ff26b04686196ac37ed849afbcfc01b303b3f/src/nf_filter_barcodes.py#L133
and
https://github.com/shendurelab/MPRAflow/blob/fd5ff26b04686196ac37ed849afbcfc01b303b3f/src/nf_filter_barcodes.py#L142

**Comment by townsk** [comment]
Plotting the violin plots does seem to be the issue - once line 133 and 142 are commented out it runs and creates the filtered barcode pickle file.

**Comment by visze** [comment]
thanks. good to know that it worked now. But strange that it fails creating the plots. I can imagine 3 possible issues:

1. Large data, to many datapoints for plotting
2. plotting/graphical issue on your system
3. seaborn library issue (we are using version 0.9.0, maybe we need to update)


But I can only debug this wehn you give me your input data.

**Comment by visze** [comment]
I will close this because I cannot debug it without the data.
