### ISSUE TITLE
Error with map_element_barcodes during Assocation: AttributeError: Can only use .str accessor with string values!

### ISSUE THREAD

**Issue by townsk** [shendurelab/MPRAflow#40]
Any thoughts? At first I thought it was an issue with the formatting of my label file, but even when I don't include a label file i get the same error. I wasn't having this issue before though - so I'm not sure what has changed. 
<img width="1760" alt="Screen Shot 2021-04-20 at 6 19 07 PM" src="https://user-images.githubusercontent.com/56935409/115474874-70296380-a20c-11eb-9621-6e872425bf6a.png">

**Comment by visze** [comment]
Which version do you use?

townsk ***@***.***> schrieb am Mi., 21. Apr. 2021, 01:12:

**Comment by townsk** [comment]
This is the input.
<img width="1765" alt="Screen Shot 2021-04-20 at 6 18 33 PM" src="https://user-images.githubusercontent.com/56935409/115547727-997dda00-a274-11eb-9b8a-f2c93b35c4ab.png">

**Comment by visze** [comment]
sorry, to be precise: can you check by yourself the input files of this process. You can find them in the work directory.

**Comment by townsk** [comment]
Ah, gotcha it looks like the TD005294_MPRA-Library-A_assoc_basic-Labeled_coords_to_barcodes.pickle file only has a few entrees. And here are the .command.log and .command.err files too.
<img width="1201" alt="Screen Shot 2021-04-21 at 10 27 50 AM" src="https://user-images.githubusercontent.com/56935409/115572658-19646e00-a28e-11eb-92e2-f7f1243022c0.png">
<img width="1202" alt="Screen Shot 2021-04-21 at 10 28 37 AM" src="https://user-images.githubusercontent.com/56935409/115572682-1e292200-a28e-11eb-8570-d4aa2df2be39.png">

**Comment by visze** [comment]
@townsk any news here. Is this still an issue?

**Comment by visze** [comment]
close because of inactivity.

please open again if needed
