### ISSUE TITLE
Using MPRAflow on data sequenced using different sequencing set-up

### ISSUE THREAD

**Issue by erykdun-dioscuri** [shendurelab/MPRAflow#72]
Hello,

I want to use MPRAflow for an assay using modified lentiMPRA plasmids. I want to modify sequencing primers to use standard Illumina primers.
How would MPRAflow deal with such modification? Do I need to modify the software to accommodate sequencing using different primers?

Thank you in advance!

Best,
Eryk

**Comment by visze** [comment]
Hi Eryk,

of course you can use different sequencing primers. It should not make any difference.

Best,
Max
